site_name: Pendulum documentation

theme:
  name: null
  custom_dir: theme

extra:
  version: 2.0

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - toc:
      permalink: 
  - markdown_include.include:
      base_path: docs
